# Generated by Django 3.2.3 on 2022-03-09 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0002_auto_20220309_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
