# Generated by Django 3.2.3 on 2022-03-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0005_tickett'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
