# Generated by Django 3.2.3 on 2022-03-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0007_tickett_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket_booking',
        ),
    ]
