# Generated by Django 3.2.3 on 2022-03-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0008_delete_ticket_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickett',
            name='timevalid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
