# Generated by Django 2.2 on 2022-03-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0009_tickett_timevalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('monument', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('count_adult', models.IntegerField()),
                ('count_chidren', models.IntegerField()),
                ('count_abroad', models.IntegerField()),
                ('price_adult', models.DecimalField(decimal_places=1, max_digits=7)),
                ('price_children', models.DecimalField(decimal_places=1, max_digits=7)),
                ('price_abroad', models.DecimalField(decimal_places=1, max_digits=7)),
                ('total_cost', models.CharField(max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('timevalid', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tickett',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
