# Generated by Django 2.2 on 2022-03-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0010_auto_20220321_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonumentTicket',
        ),
    ]
