# Generated by Django 3.2.3 on 2022-03-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0013_auto_20220321_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monumentticket',
            old_name='count_chidren',
            new_name='count_children',
        ),
    ]
