# Generated by Django 3.2.3 on 2022-03-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0014_rename_count_chidren_monumentticket_count_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('monument', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('count_adult', models.IntegerField()),
                ('count_children', models.IntegerField()),
                ('count_abroad', models.IntegerField()),
                ('price_adult', models.DecimalField(decimal_places=1, max_digits=7)),
                ('price_children', models.DecimalField(decimal_places=1, max_digits=7)),
                ('price_abroad', models.DecimalField(decimal_places=1, max_digits=7)),
                ('total_cost', models.CharField(max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('timevalid', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('total_count', models.IntegerField()),
                ('doc_type', models.CharField(max_length=20)),
                ('personal_id_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='MonumentTicket',
        ),
    ]
